---
- name: Import the public key
  apt_key: keyserver=keyserver.ubuntu.com id=EA312927
- name: add repository
  apt_repository: repo='deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse' state=present filename='mongodb' update_cache=yes
- name: install mongodb
  apt: name=mongodb-org state=present
- name: start mongodb service
  service: name=mongod state=started enabled=yes
- name: copy disable-transparent-hugepages script
  copy: src=../files/disable-transparent-hugepages dest=/etc/init.d/disable-transparent-hugepages owner=root group=root mode=0755
- name: configure disable-transparent-hugepages
  shell: update-rc.d disable-transparent-hugepages defaults
- name: check mongodb online
  wait_for: port=27017 delay=1
