---
- name: pre install packages
  apt:
     name: "{{ packages }}"
     state: present
     update_cache: true
  vars:
     packages:
      - apt-transport-https
      - gnupg
- name: Import the public key
  apt_key:
    url: 'https://www.mongodb.org/static/pgp/server-{{ version }}.asc'
    id: '{{ key[version] }}'
- name: add repository ubuntu
  apt_repository:
    repo: 'deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu {{ ansible_distribution_release }}/mongodb-org/{{ version }} multiverse'
    state: present
    filename: 'mongodb'
    update_cache: no
  when: ansible_distribution == 'Ubuntu'
- name: add repository debian
  apt_repository:
    repo: 'deb http://repo.mongodb.org/apt/debian {{ ansible_distribution_release }}/mongodb-org/{{ version }} multiverse'
    state: present
    filename: 'mongodb'
    update_cache: no
  when: ansible_distribution == 'Debian'
- name: install mongodb
  apt:
    name: mongodb-org
    state: present
    update_cache: yes
- name: start mongodb service
  service:
    name: mongod
    state: started
    enabled: yes
- name: copy disable-transparent-hugepages script
  copy:
    src: "{{ role_path }}/files/disable-transparent-hugepages.systemd"
    dest: "/etc/systemd/system/disable-transparent-hugepages.service"
    owner: root
    group: root
    mode: '0755'
  notify:
    - configure disable-transparent-hugepages
# - name: copy disable-transparent-hugepages script
#   copy:
#     src: "{{ role_path }}/files/disable-transparent-hugepages"
#     dest: /etc/init.d/disable-transparent-hugepages
#     owner: root
#     group: root
#     mode: '0755'
#   notify:
#     - configure disable-transparent-hugepages
# /etc/systemd/system/disable-transparent-huge-pages.service
- name: check mongodb online
  wait_for:
    port: 27017
    delay: 1
- name: config mongodb
  template:
    src: "{{ role_path }}/files/mongod.conf.j2"
    dest: "{{ config_path }}"
  when: config_path is defined
