---
- name: Pre install packages
  ansible.builtin.apt:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - apt-transport-https
      - gnupg
# - name: Import the public key
#   ansible.builtin.apt_key:
#     url: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
#     id: "{{ key[mongodb_version] }}"
- name: Add repository ubuntu
  ansible.builtin.deb822_repository:
    name: mongodb
    uris: "https://repo.mongodb.org/apt/ubuntu"
    suites: "{{ ansible_facts['distribution_release'] }}/mongodb-org/{{ mongodb_version }}"
    components: "multiverse"
    architectures: "amd64,arm64"
    signed_by: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present
    enabled: true
  when: ansible_facts['distribution'] == 'Ubuntu'
- name: Add repository debian
  ansible.builtin.deb822_repository:
    name: mongodb
    uris: "http://repo.mongodb.org/apt/debian"
    suites: "{{ ansible_facts['distribution_release'] }}/mongodb-org/{{ mongodb_version }}"
    components: "multiverse"
    architectures: "amd64,arm64"
    signed_by: "https://www.mongodb.org/static/pgp/server-{{ mongodb_version }}.asc"
    state: present
    enabled: true
  when: ansible_facts['distribution'] == 'Debian'
- name: Install mongodb
  ansible.builtin.apt:
    name: mongodb-org
    state: present
    update_cache: true
- name: Start mongodb service
  ansible.builtin.systemd:
    name: mongod
    state: started
    enabled: true
- name: Copy enable-transparent-hugepages script
  ansible.builtin.copy:
    src: "{{ role_path }}/files/enable-transparent-huge-pages.service"
    dest: "/etc/systemd/system/enable-transparent-huge-pages.service"
    owner: root
    group: root
    mode: "0755"
  when: enable_transparent_hugepages
  notify:
    - Configure enable-transparent-hugepages
# - name: copy disable-transparent-hugepages script
#   copy:
#     src: "{{ role_path }}/files/disable-transparent-hugepages"
#     dest: /etc/init.d/disable-transparent-hugepages
#     owner: root
#     group: root
#     mode: '0755'
#   notify:
#     - configure disable-transparent-hugepages
# /etc/systemd/system/disable-transparent-huge-pages.service
- name: Check mongodb online
  ansible.builtin.wait_for:
    port: 27017
    delay: 1
- name: Config mongodb
  ansible.builtin.template:
    src: "{{ role_path }}/files/mongod.conf.j2"
    dest: "{{ config_path }}"
    owner: mongodb
    group: mongodb
    mode: "0640"
  when: config_path is defined
  notify:
    - Restart mongodb service
