---
# handlers file for mongodb
- name: restart mongodb service
  service:
    name: mongod
    state: restarted
    enabled: yes
- name: configure disable-transparent-hugepages
  shell: update-rc.d disable-transparent-hugepages defaults