---
- name: Converge
  hosts: all
  vars:
    ansible_user: ansible
  roles:
    - name: "ansible-mongodb"
      version: 4.0
      become: true
  # tasks:
  #   - name: "Include ansible-mongodb"
  #     vars:
  #       version: 4.2
  #     include_role:
  #       name: "ansible-mongodb"
