name: Molecule Test

on:
  push:
    branches:
      - master
      - test
      - create-workflow/*
  pull_request:
    branches:
      - master
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          - 3.6
    steps:
      - uses: actions/checkout@v2.1.0
        # with:
        #   path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: python3 -m pip install 'molecule[docker]'
      - name: check molecule exists
        run: molecule --version
      - name: Run mongodb 4.2 test
        run: molecule test --scenario-name 4.2
      - name: Run mongodb 4.0 test
        run: molecule test --scenario-name 4.0
      - name: Run mongodb 3.6 test
        run: molecule test --scenario-name 3.6
      - name: Run mongodb 3.4 test
        run: molecule test --scenario-name 3.4
      - name: Run mongodb 3.2 test
        run: molecule test --scenario-name 3.2
      # - name: Run mongodb ${{test-version}} test
      #   run: molecule test --scenario-name ${{matrix.config.test-version}}