---
name: Molecule Test

on:
  push:
    branches:
      - master
      - test
      - create-workflow/*
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      max-parallel: 4
      matrix:
        os:
          - ubuntu-18.04
        python-version:
          - 3.6
        # test-version:
        #   - 4.2
        #   - 4.0
        #   - 3.6
        #   - 3.4
        #   - 3.2
    steps:
      - uses: actions/checkout@v1
        with:
          path: molecule_demo
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          sudo apt install docker
          python3 -m pip install --upgrade pip
          python3 -m pip install 'molecule[docker]'
      - name: Run mongodb 4.2 test
        run: molecule test --scenario-name 4.2
      # - name: Run mongodb ${{test-version}} test
      #   run: molecule test --scenario-name ${{matrix.test-version}}
      # - name: Run mongodb 3.0 test
      #   run: molecule test --scenario-name 3.0