name: Ansible-Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
      - test
      - create-workflow/*
jobs:
  test:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        version:
          - 4.2
          - 4.0
          - 3.6
          - 3.4
          - 3.2
        os:
          - ubuntu-18.04
      #   python-version:
      #     - 3.6
    steps:
      - uses: actions/checkout@v2.1.0
        # with:
        #   path: molecule_demo
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Install dependencies
        run: python3 -m pip install 'molecule[docker]'
      - name: check molecule exists
        run: molecule --version
      - name: Run mongodb ${{matrix.test-version}} test
        run: molecule test --scenario-name ${{matrix.test-version}}
